### ISSUE TITLE
Cannot build the .ez file

### ISSUE THREAD

**Issue by haljin** [whitfin/rabbitmq-delimiter-exchange#4]
Hi, it seems I cannot build the `.ez` file based off the description in the README. The docker container build you use for testing is failing to build as well. I don't know if something changed in `erlang.mk` or what happened, but I am not sure how can I generate this file using anything else.

**Comment by whitfin** [comment]
I just checked and updated the Docker build, so if you follow what's in there you should be good to go. RabbitMQ changed their repository structures and it broke a lot of stuff.
